### ISSUE TITLE
Configuring GitHub OAuth

### ISSUE THREAD

**Issue by andrijaperovic** [armory/spinnaker-operator#166]
Currently evaluating Spinnaker operator for migrating some existing Spinnaker pipelines which we have running in our development and production environments. 

Would like to use GitHub OAuth configurations to link our DNS Spinnaker environment to our GitHub Enterprise instance, however the only instructions available which are existing are for configuration through (legacy) halyard:
https://docs.armory.io/docs/spinnaker-install-admin-guides/authn-github/#configuring-spinnaker-with-halyard

Any idea of how this might be accomplished using operator (wasn't able to find anything in the basic or complete CRD examples)? Is this something which is part of the development roadmap?

**Comment by devorbitus** [comment]
Something like this? https://github.com/armory/spinnaker-kustomize-patches/blob/master/security/patch-github.yml

**Comment by andrijaperovic** [comment]
Thanks @devorbitus ! Will give it a try.

**Comment by devorbitus** [comment]
No problem, tons of good examples in that repo too

**Comment by andrijaperovic** [comment]
Seeing a 403 in the redirect on Spinnaker gate: 
```
2020-08-27 04:03:22.483 ERROR 1 --- [0.0-8084-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:83) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:246) ~[spring-security-oauth2-2.3.5.RELEASE.jar:na]
```

**Comment by devorbitus** [comment]
did you update the redirect URL inside the GitHub oauth configuration?

**Comment by andrijaperovic** [comment]
Yes, I've set the authorization callback URL as `https://spinnaker-gate.my.domain/login`.

**Comment by andrijaperovic** [comment]
Also, I see that after the redirect to the userAuthorizationUri (`/login/oauth/authorize`) it redirects to the enterprise GitHub URL, and then to `github.com`, so the URL ends up being something like:
```
https://github.com/login/oauth/authorize?client_id=client_id&redirect_uri=http://spinnaker-gate.my.domain/login&response_type=code&scope=user:email&state=FeHylQ
```

**Comment by andrijaperovic** [comment]
Could also be potentially linked to NPE thrown on front50 with AzureStorageService access: 
```
java.lang.NullPointerException: null
	at com.netflix.spinnaker.front50.model.AzureStorageService.logStorageException(AzureStorageService.java:295) ~[front50-azure.jar:na]
	at com.netflix.spinnaker.front50.model.AzureStorageService.getLastModified(AzureStorageService.java:257) ~[front50-azure.jar:na]
	at com.netflix.spinnaker.front50.model.StorageServiceSupport.readLastModified(StorageServiceSupport.java:454) ~[front50-core.jar:na]
	at com.netflix.spinnaker.front50.model.StorageServiceSupport.all(StorageServiceSupport.java:159) ~[front50-core.jar:na]
	at com.netflix.spinnaker.front50.model.StorageServiceSupport.all(StorageServiceSupport.java:151) ~[front50-core.jar:na]
	at com.netflix.spinnaker.front50.model.ItemDAO$all$0.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.front50.controllers.PermissionsController.getAllApplicationPermissions(PermissionsController.groovy:57) ~[front50-web.jar:na]
	at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source) ~[na:na]
```

**Comment by devorbitus** [comment]
Which are you using, GHE or GH?

**Comment by andrijaperovic** [comment]
@devorbitus using GHE.

**Comment by devorbitus** [comment]
did you change [this line](https://github.com/armory/spinnaker-kustomize-patches/blob/master/security/patch-github.yml#L38) to the correct API address or your GHE?

**Comment by andrijaperovic** [comment]
Yes.

**Comment by andrijaperovic** [comment]
@devorbitus is `github.com` hard-coded anywhere, such that it would redirect to `github.com` instead of the GHE `baseUrl` after going to spinnaker gate?

**Comment by devorbitus** [comment]
it is not hardcoded anywhere, it respects the baseUrl property but you should try calling the `github.mycoolcompany.com/api/v3` endpoint with curl to see if you get a response. Then try with the access token using authentication and curl to see if you can get in. If all of those work then it must be a config issue and you would need to sanitize the config and post the kustomize patch file you are using to configure it so can look it over

**Comment by andrijaperovic** [comment]
OK will try the curl to the `/api/v3` endpoint to see if the access token is retrievable.
Here is the CRD we are applying:

```
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        authn:
          enabled: true
          oauth2:
            enabled: true
            client:
              clientId: client_id                                   # The OAuth client ID you have configured with your OAuth provider.
              clientSecret: client_secret           # (Secret). The OAuth client secret you have configured with your OAuth provider.
              accessTokenUri: https://github.mycoolcompany.com/login/oauth/access_token      # Used to get an access token.
              userAuthorizationUri: https://github.mycoolcompany.com/login/oauth/authorize   # Used to get an authorization code.
              scope: read:org,user:email                                                # The scope for your OAuth provider, e.g. user:email
            resource:
              userInfoUri: https://github.mycoolcompany.com/api/v3/user                         # Used to the current user's profile.
            userInfoMapping:
              email: email                                                     # The email field returned from your OAuth provider.
              firstName: name                                                  # The first name field returned from your OAuth provider.
              lastName: ""                                                     # The last name field returned from your OAuth provider.
              username: login                                                  # The username field returned from your OAuth provider.
            provider: GITHUB                                                   # One of AZURE, GITHUB, ORACLE, OTHER, GOOGLE
        authz:
          enabled: true
          groupMembership:
            service: GITHUB                             # One of EXTERNAL, FILE, GOOGLE, GITHUB, LDAP
            github:
              roleProviderType: GITHUB
              baseUrl: https://github.mycoolcompany.com/api/v3/          # Used if using GitHub enterprise or some other non github.com GitHub installation.
              accessToken: access_token # (Secret). A personal access token of an account with access to your organization’s GitHub Teams structure. Supports encrypted value.
              organization: MYORG                       # The GitHub organization under which to query for GitHub Teams.
        apiSecurity:
          overrideBaseUrl: https://spinnaker-gate.my.domain  # Specify your DNS name for Gate with https scheme
        uiSecurity:
          overrideBaseUrl: https://spinnaker.my.domain       # Specify your DNS name for Deck with https scheme
      version: 1.17.1   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: azs
        azs:
          storageAccountName: storageaccountname
          storageAccountKey: storageaccountkey
          storageContainerName: spinnaker
  # spec.expose - This section defines how Spinnaker should be publicly exposed
  expose:
    type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
    service:
      type: ClusterIP
```

**Comment by devorbitus** [comment]
when you try it with curl you can just use basic auth with the token as the password

**Comment by andrijaperovic** [comment]
Token works: 
```
curl --user :fb8a6378d011bf8d57bd1b3376576dc1d7b7b53d https://github.my.domain/api/v3                                              master@78500a0 ✘
{
  "current_user_url": "https://github.my.domain/api/v3/user",
  "current_user_authorizations_html_url": "https://github.my.domain/settings/connections/applications{/client_id}",
  "authorizations_url": "https://github.my.domain/api/v3/authorizations",
  "code_search_url": "https://github.my.domain/api/v3/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://github.my.domain/api/v3/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://github.my.domain/api/v3/user/emails",
  "emojis_url": "https://github.my.domain/api/v3/emojis",
  "events_url": "https://github.my.domain/api/v3/events",
  "feeds_url": "https://github.my.domain/api/v3/feeds",
  "followers_url": "https://github.my.domain/api/v3/user/followers",
  "following_url": "https://github.my.domain/api/v3/user/following{/target}",
  "gists_url": "https://github.my.domain/api/v3/gists{/gist_id}",
  "hub_url": "https://github.my.domain/api/v3/hub",
  "issue_search_url": "https://github.my.domain/api/v3/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://github.my.domain/api/v3/issues",
  "keys_url": "https://github.my.domain/api/v3/user/keys",
  "label_search_url": "https://github.my.domain/api/v3/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
  "notifications_url": "https://github.my.domain/api/v3/notifications",
  "organization_repositories_url": "https://github.my.domain/api/v3/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_url": "https://github.my.domain/api/v3/orgs/{org}",
  "public_gists_url": "https://github.my.domain/api/v3/gists/public",
  "rate_limit_url": "https://github.my.domain/api/v3/rate_limit",
  "repository_url": "https://github.my.domain/api/v3/repos/{owner}/{repo}",
  "repository_search_url": "https://github.my.domain/api/v3/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://github.my.domain/api/v3/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://github.my.domain/api/v3/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://github.my.domain/api/v3/gists/starred",
  "team_url": "https://github.my.domain/api/v3/teams",
  "user_url": "https://github.my.domain/api/v3/users/{user}",
  "user_organizations_url": "https://github.my.domain/api/v3/user/orgs",
  "user_repositories_url": "https://github.my.domain/api/v3/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://github.my.domain/api/v3/search/users?q={query}{&page,per_page,sort,order}"
}
```

**Comment by devorbitus** [comment]
next, I would try and see if works from inside one of the pods like clouddriver using curl

**Comment by andrijaperovic** [comment]
Looks like the issue was that I had to run `delete -f`, then `apply -f` on the CRD.
However, seeing infinite redirects between `github.my.domain` and spinnaker gate, with 422 in the spinnaker gate logs: 

```
2020-08-27 05:50:28.308 ERROR 1 --- [0.0-8084-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.web.client.HttpClientErrorException$UnprocessableEntity: 422 Unprocessable Entity
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:99) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:246) ~[spring-security-oauth2-2.3.5.RELEASE.jar:na]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:691) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
```

```
2020-08-27 05:50:28.351  INFO 1 --- [applications-10] c.n.s.g.s.internal.Front50Service        : java.net.ConnectException: Failed to connect to spin-front50.spinnaker/10.0.87.86:8080
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
```

**Comment by punitmishra** [comment]
@andrijaperovic apparently the re-direct URL always goes to http, changing the authorization call back URL to http:// in the auth call back of github enterprise seems to have worked. 

![image](https://user-images.githubusercontent.com/727059/91408662-0c73a580-e7f9-11ea-80c9-3a4a28852794.png)

**Comment by devorbitus** [comment]
so, good then?

**Comment by andrijaperovic** [comment]
Yup, thanks @devorbitus ! Not sure why `http://` is required for the authorization callback URL, but we can close this one out for now.

**Comment by c-o-n-n-e-r** [comment]
I am having a similar issue where Spinnaker seems to ignore `spec.spinnakerConfig.config.security.authz.groupMembership.github.baseUrl` and calls back using https://github.com rather than the Url of my GHE provided in the SpinnakerService yaml.

```
spec:
  spinnakerConfig:
    config:
      version: 1.17.1
      security:
        apiSecurity:
          overrideBaseUrl: https://my-spinnaker-gate.io
        uiSecurity:
          overrideBaseUrl: https://my-spinnaker-deck.io
        authn:
          oauth2:
            enabled: true
            client:
              userAuthorizationUri: https://my-ghe.io/login/oauth/access_token
              accessTokenUri: https://my-ghe.io/login/oauth/authorize
              clientId: myclientid
              clientSecret: myclientsecret
              scope: read:org,user:email
              preEstablishedRedirectUri: https://my-spinnaker-gate.io/login
            resource:
              userInfoUri: https://my-ghe.io/api/v3/user
            userInfoMapping:
              email: email
              lastName: name
              username: login
            provider: GITHUB
        authz:
          enabled: true
          groupMembership:
            service: GITHUB
            github: 
              roleProviderType: GITHUB
              baseUrl: https://my-ghe.io/api/v3
              organization: my-org
              accessToken: myaccesstoken
```
Am I missing something here?
